bcgov/business-ui

- business-registry-dashboard/app/stores/affiliations.ts
- business-registry-dashboard/package.json
Ticket #: https://github.com/bcgov/entity/issues/24979
Fixed no affiliation records showing on initial page load which is wrong since it's showing before the affiliations are actually loaded.
> fix: fixed no affiliation records showing before load

- business-registry-dashboard/app/components/Table/AffiliatedEntity/Action.vue
- business-registry-dashboard/app/composables/useAffiliationNavigation.ts
- business-registry-dashboard/package.json
https://github.com/bcgov/entity/issues/25076
NRs for entity types not in the FF redirect to COLIN; left as is.
Existing businesses route now to Business Dashboard -- don't check FF.
Basically:
If type is NR, we are checking the `ia-supported-entities-brd` FF. If the FF doesn't support the type, redirect to COLIN.
For existing businesses though, we no more check the FF. We will ALWAYS go to the business dashboard with that business.
> fix: existing businesses route to business dashboard (removed FF check)

- business-registry-dashboard/app/layouts/dashboard.vue
- business-registry-dashboard/package.json
https://github.com/bcgov/entity/issues/25148
This is an ATTEMPT. I can't recreate this issue in neither local nor DEV. It's only in TEST and PROD. I'm pretty sure the issue is:
The page is loading before the keycloak/authentication check is done. I'm hoping my fix here fixes it.
To see what's exactly happening, just try to go to https://business-registry-test.web.app/en-CA
> fix: fix infinite redirect loop in TEST and PROD

- business-registry-dashboard/app/components/HelpTextSection.vue
- business-registry-dashboard/app/locales/en-CA.ts
- business-registry-dashboard/app/locales/fr-CA.ts
- business-registry-dashboard/package.json
https://github.com/bcgov/entity/issues/25286
Fixed this:
Previously, that help text was being rendered by a markdown (.md) file. Every time I tried a fix, it WORKS locally but when I create a temp link, it DOESN'T work. I kept going back and forth many times but to no avail. You can tell by the amount of comments deleted 😁 
So, I decided to move away altogether from using those markdown files for now. I want to get this moved forward because I need to be done with this and another ticket by tomorrow.
> fix: fixed the "you should use slots with <ContentRenderer>" error

- business-registry-dashboard/app/components/Table/AffiliatedEntity/Action.vue
- business-registry-dashboard/app/enums/business-state.ts
- business-registry-dashboard/app/interfaces/affiliation.ts
- business-registry-dashboard/app/interfaces/business.ts
- business-registry-dashboard/app/utils/affiliations.ts
- business-registry-dashboard/app/utils/business.ts
- business-registry-dashboard/package.json
Issue #: /https://github.com/bcgov/entity/issues/24660
- Add the status of Withdrawn in BRD
- Add withdrawn status filter to the BRD
- with action to remove it from BRD Remove from table option is available when user selects the drop down
- Primary action is to "Manage Business"
- When user selects "Manage Business" display entity dashboard
> 24660 - Display Withdrawn Status in BRD

- business-registry-dashboard/app/pages/incorporateNow.vue
- business-registry-dashboard/package.json
https://github.com/bcgov/entity/issues/25427
Before I approved my NR:
If you take a look at the console, the expiration date is null. As long as that expiration date is null, the NR isn't fully ready to be consumed yet. So, we'll show that nice error dialog.
> fixed: incorp now link to show dialog error if NR not processed yet

- business-registry-dashboard/app/components/Modal/RemoveBusiness/Generic.vue
- business-registry-dashboard/app/components/Table/AffiliatedEntity/Action.vue
- business-registry-dashboard/app/composables/useBrdModals.ts
- business-registry-dashboard/app/locales/en-CA.ts
- business-registry-dashboard/app/locales/fr-CA.ts
- business-registry-dashboard/app/stores/affiliations.ts
- business-registry-dashboard/package.json
- business-registry-dashboard/tests/unit/composables/useBrdModals.test.ts
Issue #: https://github.com/bcgov/entity/issues/22683
Description of changes:
- Updated logic so that Continue In's would be successfully deleted or removed (have affiliations removed). 
- Added in wording in accordance with the Figma design here: https://www.figma.com/design/rNe2jn8wyFykKRzwiBo6ar/Continuation-In-V6?node-id=2188-39977&p=f&t=e3LnVAu9pjqKCmAb-0
- Refactored some related code
Also addresses following tickets:
Issue #: https://github.com/bcgov/entity/issues/24079
Issue #: https://github.com/bcgov/entity/issues/24986
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the business-filings-ui license (Apache 2.0).
> 22683 remove delete continuation functionality

- business-registry-dashboard/app/utils/affiliations.ts
- business-registry-dashboard/package.json
- business-registry-dashboard/tests/unit/utils/affiliations.test.ts
https://github.com/bcgov/entity/issues/26375
Inconsistency in how Zombie corps are displayed in BRD. Now empty string for all to stay consistent (as was decided).
> fix: fixed inconsistency in how to display zombie corps

- business-registry-dashboard/app/stores/affiliations.ts
- business-registry-dashboard/package.json
- business-registry-dashboard/tests/unit/stores/affiliations.test.ts
https://github.com/bcgov/entity/issues/26365
Fixed the error when trying to remove withdrawn filings.
I wasted a ton of time thinking it was a LEAR issue. I went to legal api and tried fixing the DELETE endpoint to support withdrawn filings. I realized that would delete the withdrawn filing entirely from the DB (we need to keep some record of those withdrawn filings) though so I shifted back here. We just need to delete it using that remove affiliation function where it makes that Auth API call.
> 26365 fixed removing withdrawn filings error

- business-registry-dashboard/app/utils/reg-search.ts
- business-registry-dashboard/package.json
- business-registry-dashboard/pnpm-lock.yaml
*Issue #:* bcgov/entity#26471
- app version = 1.0.28
- removed App-Name from reg-search
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache 2.0).
> 26471 removed App-Name from namex-search and reg-search

- business-registry-dashboard/app/utils/reg-search.ts
- business-registry-dashboard/package.json
*Issue #:* bcgov/entity#26471
_SB says: well, I was told that updating the Reg Search API was low priority, but then Kial and Doug fixed the API gateway config (in all environments) yesterday. So here we are, adding the App Name header back in for these API calls._
- app version = 1.0.29
- added App-Name to reg search calls
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache 2.0).
> 26471 added App-Name to reg-search

- business-registry-dashboard/app/components/BCReg/ContactInfo.vue
- business-registry-dashboard/app/components/Modal/Base.vue
- business-registry-dashboard/app/components/Table/AffiliatedEntity/Action.vue
- business-registry-dashboard/app/components/Table/AffiliatedEntity/index.vue
- business-registry-dashboard/app/composables/useAffiliationNavigation.ts
- business-registry-dashboard/app/composables/useBrdModals.ts
- business-registry-dashboard/app/locales/en-CA.ts
- business-registry-dashboard/app/locales/fr-CA.ts
- business-registry-dashboard/app/utils/business.ts
- business-registry-dashboard/package.json
https://github.com/bcgov/entity/issues/26607
Added error dialog when trying to perform an action like "Register Now" in the BRD (usually happens if Legal API failed to create a draft):
~I just need to confirm the text with Jacqueline~ Design: https://www.figma.com/design/6MBqd7QAijpl6OXLvLXmos/Errors?node-id=89-71&p=f&m=dev
> feat: implemented error dialog for name request actions

- business-registry-dashboard/app/stores/connect-launchdarkly.ts
- business-registry-dashboard/package.json
https://github.com/bcgov/entity/issues/27067
OK, here's a bit of info what I did here:
First and foremost, I moved the LD store out of the nuxt daxiom shared package. The store used to be here:
`business-ui\business-registry-dashboard\node_modules\@daxiom\nuxt-core-layer-test\app\stores`
Now, I don't know if Thor will like this but I needed to do that in order to make my own changes. The changes being correctly reporting the context to LD when an org/user is changed. 
- I added some additional `console.info` to see what's going on
- The context is updated and sent to LD on user/org change.
Here's how I tested:
I logged in as BCREG0020 which defaults to resd right. The contexts in LD are:
You can see up top 668 which is the org id for resd. 
Now, let's change the account to mine: 
The …
> 27067 - Fixed LD targetting + wrong user reporting

- business-registry-dashboard/app/enums/display-name-to-corp-type.ts
- business-registry-dashboard/package.json
I don't have a ticket for this so I'm just going to put Rajan's ticket https://github.com/bcgov/entity/issues/27148
https://auth-api-dev-142173140222.northamerica-northeast1.run.app/api/v1/orgs/3040/affiliations?new=true&type=Extraprovincial%20Company&page=1&limit=100
is now
https://auth-api-dev-142173140222.northamerica-northeast1.run.app/api/v1/orgs/3040/affiliations?new=true&type=A&page=1&limit=100
> added extraprovincial companies to server side type filtering

- web/person-roles/app/components/Form/OfficerChange/index.vue
- web/person-roles/package.json
bcGov/entity#27631
- fix reactivity between mailing/delivery address when selecting sameAsDelivery checkbox
- remove redundant if/else in region schema
- add 'mailingAddress.country' to list of fields to clear when sameAs checkbox selected
> Officer reactivity address bug

- business-registry-dashboard/app/stores/affiliations.ts
- business-registry-dashboard/package.json
https://github.com/bcgov/entity/issues/27629
Fixed infinite loop of calls to affiliations endpoint when one FF is enabled
> 27629 - Fixed infinite loop of calls to affiliations endpoint + misc. fixes

- business-registry-dashboard/app/stores/affiliations.ts
- business-registry-dashboard/package.json
https://github.com/bcgov/entity/issues/27629
Sev found a bug. Let's say you type NR4 and then the table starts loading. While the table is loading, if you type x after 4, the results will still be for NR4 which is very bad user experience honestly and will be probably frustrating for users. This PR fixes this. 
I also added a minimum requirement for how many characters is needed. Sev, please if you can test the bug in the temp link, that would be great. Thanks.
> 27629 - Fixed text filtering bug + put minimum characters

- business-registry-dashboard/app/layouts/dashboard.vue
- business-registry-dashboard/package.json
https://github.com/bcgov/entity/issues/27580
When we switch from resd to Karim Dev Account for example, the URL will properly reflect that. That was causing functionality issues.
> 27580 - Fixed account switching to properly reflect in URL

- business-registry-dashboard/app/components/Table/AffiliatedEntity/Action.vue
- business-registry-dashboard/app/composables/useBrdModals.ts
- business-registry-dashboard/app/locales/en-CA.ts
- business-registry-dashboard/app/locales/fr-CA.ts
- business-registry-dashboard/package.json
https://github.com/bcgov/entity/issues/27567
**EXAMPLE SCENARIO:**
I have two tabs open with a name request that's approved. I create a draft business in one tab and go all the way to completion. Now in tab number two, if I click on the register now button, we show an alert. This is since the NR is now consumed. This can happen for other situations like the NR expiring for example. 
I got the greenlight for the design of the dialog from Jacqueline. She's OK with this.
> 27567 - Alert when using non-approved NRs to create business

- web/business-registry-dashboard/.eslintrc
- web/business-registry-dashboard/app/components/Form/AddBusiness/Base.vue
- web/business-registry-dashboard/app/components/Modal/ManageBusiness.vue
- web/business-registry-dashboard/app/locales/en-CA.ts
- web/business-registry-dashboard/app/locales/fr-CA.ts
- web/business-registry-dashboard/package.json
- web/business-registry-dashboard/tests/unit/components/Form/AddBusiness/FormAddBusinessBase.test.ts
https://github.com/bcgov/entity/issues/27275
Designs Implemented: https://www.figma.com/design/e8EFtixUQ9sZiKKBSleXHq/Affiliation?node-id=2928-10872&m=dev
Changes:
- Changed from using accordions to radio buttons in the affiliation modal
- No buttons or accordions when there are no options. Removed the divider when there are no options as per the designs.
- No radio when there is one option and the text is bolded of the action
- Radio buttons unselected when there are two or more options
- Bold the text of the selected action
- Implemented specific design for radio buttons in the design link. Borders are blue. Used a special class there. 
- Fixed spacing and made sure things look good as per the designs. 
- Fixed unit tests
> 27275 - Moved from Accordions to Radio Buttons in affiliation modals

- web/business-registry-dashboard/app/components/Table/AffiliatedEntity/index.vue
- web/business-registry-dashboard/app/interfaces/affiliation.ts
- web/business-registry-dashboard/app/locales/en-CA.ts
- web/business-registry-dashboard/app/locales/fr-CA.ts
- web/business-registry-dashboard/app/stores/affiliations.ts
- web/business-registry-dashboard/app/stores/connect-launchdarkly.ts
- web/business-registry-dashboard/package.json
https://github.com/bcgov/entity/issues/28976
Changes:
- No more all the page numbers. We can only go left and right.
- Show the page we're at RIGHT NOW.
- Go left and right buttons
- My list doesn't have the count now (if pagination is enabled)
- We can go right only if the hasMore flag is true. 
- Fixed some small bugs (make the right call when page limit is change while we're not on page 1)
> 28976 - Changed pagination controls + use isMore flag + misc. fixes

- web/business-registry-dashboard/app/composables/useMagicLinkProcessing.ts
- web/business-registry-dashboard/app/layouts/dashboard.vue
- web/business-registry-dashboard/app/stores/affiliations.ts
- web/business-registry-dashboard/package.json
https://github.com/bcgov/entity/issues/29145 and https://github.com/bcgov/entity/issues/29148
I'm changing my account from resd to Karim Dev account while I was on page 2. The call was still being made to page 2 and the table was showing empty.
I have a handful of stuff in Karim Dev Account so that's why. This can be very misleading to users.
We now reset to page 1 on account switching.
Mihai was telling me that magic links weren't being processed at all and he was right. I fixed that here as well.
> 29145 - Reset page when account is changed + fixed magic link processing

- web/post-restoration-transition-application/app/components/Shares/AddEdit.vue
- web/post-restoration-transition-application/app/components/Shares/Index.vue
- web/post-restoration-transition-application/tests/e2e/specs/series.spec.ts
*Issue #:* /bcgov/entity#29099
Disable undo on series when a share is in an incompatible state (no special rights restrictions)
Fix issue with removing special rights on a share that has series
> fix share series removal via checkbox, and block undo in invalid state
