- business-registry-dashboard/app/components/HelpTextSection.vue
- business-registry-dashboard/app/components/Table/AffiliatedEntity/Action.vue
- business-registry-dashboard/app/components/Table/AffiliatedEntity/StatusDetails.vue
- business-registry-dashboard/app/components/Table/Column/Header.vue
- business-registry-dashboard/app/locales/en-CA.ts
- business-registry-dashboard/app/locales/fr-CA.ts
- business-registry-dashboard/app/pages/index.vue
- business-registry-dashboard/app/utils/affiliations.ts
- business-registry-dashboard/app/utils/business.ts
- business-registry-dashboard/app/utils/name-request.ts
Partial: bcGov/entity#22568
- add missing translations for table
- add aria-attributes for table actions/filters
- add hidden text to table cells if extra info is required (name request accepted/rejected, status alerts, etc)
- hardcoded ld flags for now
- fix hydration error on button
> Table i18n a11y

- business-registry-dashboard/app/components/Table/AffiliatedEntity/Action.vue
- business-registry-dashboard/app/composables/useAffiliationNavigation.ts
- business-registry-dashboard/app/composables/useAffiliations.ts
- business-registry-dashboard/app/enums/nr-entity-type.ts
- business-registry-dashboard/app/pages/index.vue
- business-registry-dashboard/app/utils/affiliations.ts
- business-registry-dashboard/app/utils/business.ts
- business-registry-dashboard/nuxt.config.ts
Partial: bcGov/entity#22568
- add typing for table action emits
- implement 'createBusinessRecord' function
- add callback to navigation functions
- fix watcher making affiliations fetch on each instance of Actions component
> BRD - UI: Affiliation Table emits

- business-registry-dashboard/nuxt.config.ts
Change envvar to NUXT_REGISTRY_HOME_URL
> fix: nuxt.config.ts

- business-registry-dashboard/app/components/HelpTextSection.vue
- business-registry-dashboard/app/components/Table/Column/Header.vue
- business-registry-dashboard/app/composables/useAffiliations.ts
- business-registry-dashboard/app/locales/en-CA.ts
- business-registry-dashboard/app/locales/fr-CA.ts
- business-registry-dashboard/app/pages/index.vue
- business-registry-dashboard/content/fr-CA/start-manage-business-help-text.md
- business-registry-dashboard/tests/mocks/mockedData.ts
- business-registry-dashboard/tests/unit/composables/useAffiliations.test.ts
issue: bcGov/entity#22569
- filter table results with header options
- set table to a fixed height 
- set sticky table header
- add comments to useAffiliations composable
- test filter options in useAffiliations composable
- set loading table prop
- set empty text in table
> BRD - UI: Table filters

- business-registry-dashboard/app/app.config.ts
- business-registry-dashboard/app/components/Form/AddNameRequest/Base.vue
- business-registry-dashboard/app/components/Form/AddNameRequest/Error.vue
- business-registry-dashboard/app/components/Form/AddNameRequest/Help.vue
- business-registry-dashboard/app/components/Form/AddNameRequest/index.vue
- business-registry-dashboard/app/components/Modal/Base.vue
- business-registry-dashboard/app/components/Modal/ManageNameRequest.vue
- business-registry-dashboard/app/composables/useBrdModals.ts
- business-registry-dashboard/app/locales/en-CA.ts
- business-registry-dashboard/app/locales/fr-CA.ts
- business-registry-dashboard/app/pages/index.vue
- business-registry-dashboard/app/plugins/maska.ts
- business-registry-dashboard/nuxt.config.ts
- business-registry-dashboard/package.json
- business-registry-dashboard/pnpm-lock.yaml
partial issue: bcGov/entity#22573
- modal layout and validation for adding a name request to 'my list'
- does not include any fetch requests yet
- does not include 'name request already added' state
https://github.com/user-attachments/assets/f47a7f17-6cb7-49ee-9bf5-3b675a5df066
> BRD -UI: Manage nr initial modal layout

- business-registry-dashboard/app/components/Form/AddNameRequest/Base.vue
- business-registry-dashboard/app/components/Form/AddNameRequest/Error.vue
- business-registry-dashboard/app/components/Form/AddNameRequest/index.vue
- business-registry-dashboard/app/components/Modal/Base.vue
- business-registry-dashboard/app/composables/useAffiliations.ts
- business-registry-dashboard/app/composables/useBrdModals.ts
- business-registry-dashboard/app/enums/user-roles.ts
- business-registry-dashboard/app/locales/en-CA.ts
- business-registry-dashboard/app/locales/fr-CA.ts
- business-registry-dashboard/app/pages/index.vue
Partial: bcGov/entity#22573
- add functionality to manage name request modal
> BRD - UI: Feat - Manage nr modal functionality

- business-registry-dashboard/app/components/Modal/ManageBusiness.vue
- business-registry-dashboard/app/components/Table/AffiliatedEntity/Action.vue
- business-registry-dashboard/app/components/Table/AffiliatedEntity/index.vue
- business-registry-dashboard/app/locales/fr-CA.ts
- business-registry-dashboard/app/stores/affiliations.ts
- business-registry-dashboard/app/utils/business.ts
- business-registry-dashboard/app/utils/name-request.ts
- business-registry-dashboard/package.json
- business-registry-dashboard/pnpm-lock.yaml
- business-registry-dashboard/tests/unit/composables/useAffiliationNavigation.test.ts
- business-registry-dashboard/tests/unit/stores/affiliations.test.ts
- business-registry-dashboard/tests/unit/utils/affiliations.test.ts
- business-registry-dashboard/tests/unit/utils/business.test.ts
- business-registry-dashboard/tests/unit/utils/name-request.test.ts
issue: bcGov/entity#23356
- Implement ld flags into app
- update tests to include ld flags
> BRD- UI: Ld flags

- business-registry-dashboard/app/components/Form/AddNameRequest/Base.vue
- business-registry-dashboard/app/locales/en-CA.ts
- business-registry-dashboard/pnpm-lock.yaml
Issue #: /https://github.com/bcgov/entity/issues/23358
Changes:
- Fixed the NR phone input to match what's in the current site
BRD currently in DEV:
New one here:
> 23358 - Fixed NR phone input

- business-registry-dashboard/.env.sample
- business-registry-dashboard/app/app.config.ts
- business-registry-dashboard/app/components/BCReg/ContactInfo.vue
- business-registry-dashboard/app/components/BusinessLookup.vue
- business-registry-dashboard/app/components/Form/AddBusiness/Base.vue
- business-registry-dashboard/app/components/Form/AddBusiness/Error.vue
- business-registry-dashboard/app/components/Form/AddNameRequest/Base.vue
- business-registry-dashboard/app/components/Form/AddNameRequest/Error.vue
- business-registry-dashboard/app/components/Form/AddNameRequest/Help.vue
- business-registry-dashboard/app/components/Modal/Base.vue
- business-registry-dashboard/app/components/Modal/ManageBusiness.vue
- business-registry-dashboard/app/components/Modal/ManageNameRequest.vue
- business-registry-dashboard/app/components/Table/AffiliatedEntity/index.vue
- business-registry-dashboard/app/locales/en-CA.ts
- business-registry-dashboard/app/locales/fr-CA.ts
- business-registry-dashboard/app/stores/affiliations.ts
- business-registry-dashboard/package.json
Issue #: /https://github.com/bcgov/entity/issues/24135
Changes:
- Fixed a TON of stuff noted by our UXA team.
If you have any questions about any of the changes, please let me know, I can clarify. Everything here is in response to https://github.com/bcgov/entity/issues/23340
> fix: fixed a ton of UX issues for business affiliations

- business-registry-dashboard/app/app.config.ts
- business-registry-dashboard/app/components/Table/AffiliatedEntity/Action.vue
- business-registry-dashboard/app/pages/affiliationInvitation/acceptToken.vue
- business-registry-dashboard/app/pages/index.vue
- business-registry-dashboard/nuxt.config.ts
- business-registry-dashboard/package.json
Issue #: https://github.com/bcgov/entity/issues/24364
Fixed issues in response to Jacqueline's comment: https://github.com/bcgov/entity/issues/24364#issuecomment-2505056084
> fix: fixed UXA issues in response to Jacqueline's comment

- business-registry-dashboard/app/components/Table/AffiliatedEntity/Action.vue
- business-registry-dashboard/app/utils/business.ts
- business-registry-dashboard/package.json
*Issue #:* https://github.com/bcgov/entity/issues/24224
Updated how to handle Name change and Alteration NRs. The action button mainly. 
If business exists in LEAR --> Go to modernized system
If not --> Go to Legacy system
No more usage of feature flags.
> feat: updated handling of Name change and Alteration NRs

- business-registry-dashboard/app/stores/affiliations.ts
- business-registry-dashboard/package.json
ticket #: https://github.com/bcgov/entity/issues/24885
Fixed draft deletion of IA drafts. I added support to the other types as well.
> fix: fixed draft deletion of filings

- business-registry-dashboard/app/components/Modal/RemoveBusiness/index.vue
- business-registry-dashboard/app/locales/en-CA.ts
- business-registry-dashboard/app/locales/fr-CA.ts
- business-registry-dashboard/package.json
*Issue #:*
https://github.com/bcgov/entity/issues/24882
Fixed the toast text: 
If we're removing a business, the text will say: "Business successfully removed from your list."
If we removing a name request, the text will say: "Name Request successfully removed from your list."
> fix: fixed table row removal toast text

- business-registry-dashboard/app/layouts/dashboard.vue
- business-registry-dashboard/package.json
removed the redirection if not logged in to test keycloak adapter in TEST
> removed the redirection if not logged in to test keycloak adapter in TEST

- business-registry-dashboard/app/layouts/dashboard.vue
- business-registry-dashboard/package.json
https://github.com/bcgov/entity/issues/25148
I'm going back to the old code. TEST and PROD are now fixed thanks to Travis. We needed to add the web origins in keycloak.
> reverted the change to login redirection + removed debug code

- business-registry-dashboard/app/layouts/dashboard.vue
- business-registry-dashboard/nuxt.config.ts
- business-registry-dashboard/package.json
https://app.zenhub.com/workspaces/entities---olga-65af15f59e89f5043c2911f7/issues/gh/bcgov/entity/25255
https://app.zenhub.com/workspaces/entities---olga-65af15f59e89f5043c2911f7/issues/gh/bcgov/entity/25247
Fixed redirection with correct account id to Name Request UI
> fix: fixed redirection with correct account id to Name Request UI

- business-registry-dashboard/app/components/Modal/Base.vue
- business-registry-dashboard/app/composables/useBrdModals.ts
- business-registry-dashboard/app/locales/en-CA.ts
- business-registry-dashboard/app/locales/fr-CA.ts
- business-registry-dashboard/app/pages/incorporateNow.vue
- business-registry-dashboard/package.json
https://github.com/bcgov/entity/issues/25284
In local:
> fix: fixed the magic link incorporation error dialog text

- business-registry-dashboard/app/stores/affiliations.ts
- business-registry-dashboard/package.json
https://github.com/bcgov/entity/issues/25548
Adding BC0887553 to account 668 should properly work now, not added it to staff 3040.
I also fixed deletion as they go hand in hand.
> fix: fixed staff additions of NRs and businesses to wrong accounts

- business-registry-dashboard/app/components/Table/AffiliatedEntity/index.vue
- business-registry-dashboard/app/locales/en-CA.ts
- business-registry-dashboard/app/locales/fr-CA.ts
- business-registry-dashboard/package.json
https://github.com/bcgov/entity/issues/18374
Fixed in response to Jacquline's comment: https://github.com/bcgov/entity/issues/18374#issuecomment-2625228876
> fix: fixed UX issue for empty text in response to UXA comments

- business-registry-dashboard/app/components/Table/AffiliatedEntity/Action.vue
- business-registry-dashboard/package.json
- business-registry-dashboard/tailwind.config.ts
https://github.com/bcgov/entity/issues/25624
In response to: https://github.com/bcgov/entity/issues/25624#issuecomment-2644050052
Before:
After:
> fix: fixed primary action button width in response to UX notes

- business-registry-dashboard/app/components/Form/AddNameRequest/Base.vue
- business-registry-dashboard/package.json
https://github.com/bcgov/entity/issues/25324
Fixed the bug where an NR is unable to be affiliated although a valid email is being put.
> fix: fixed unable to affiliate an NR with a valid email

- business-registry-dashboard/app/components/Table/AffiliatedEntity/Action.vue
- business-registry-dashboard/app/composables/useBrdModals.ts
- business-registry-dashboard/app/layouts/dashboard.vue
- business-registry-dashboard/app/locales/en-CA.ts
- business-registry-dashboard/app/locales/fr-CA.ts
- business-registry-dashboard/app/utils/affiliations.ts
- business-registry-dashboard/package.json
https://github.com/bcgov/entity/issues/26194
> feat: name request expired in BRD (tooltip/icon) + misc fixes

- business-registry-dashboard/app/components/Table/AffiliatedEntity/Action.vue
- business-registry-dashboard/app/locales/en-CA.ts
- business-registry-dashboard/app/locales/fr-CA.ts
- business-registry-dashboard/package.json
https://github.com/bcgov/entity/issues/23518
Jacqueline wants the old text back.
> fix: fixed continuation in wording

- business-registry-dashboard/app/stores/affiliations.ts
- business-registry-dashboard/package.json
https://github.com/bcgov/entity/issues/26186
After pinpointing where the issue was, it was just deleting that line.
> fix: fix filters clearing if window is shrunk and vice versa

- business-registry-dashboard/.env.sample
- business-registry-dashboard/app/locales/en-CA.ts
- business-registry-dashboard/app/locales/fr-CA.ts
- business-registry-dashboard/package.json
https://github.com/bcgov/entity/issues/26358
Some entries were missing (BC, BEN, CC, ULC). I think now all has been accounted for.
> fix: fixed missing removeBusiness text entries

- business-registry-dashboard/.env.sample
- business-registry-dashboard/app/components/Table/AffiliatedEntity/Action.vue
- business-registry-dashboard/app/composables/useMagicLinkProcessing.ts
- business-registry-dashboard/app/locales/en-CA.ts
- business-registry-dashboard/app/locales/fr-CA.ts
- business-registry-dashboard/app/pages/amalgamateNow.vue
- business-registry-dashboard/app/pages/continueInNow.vue
- business-registry-dashboard/app/pages/registerNow.vue
- business-registry-dashboard/package.json
https://github.com/bcgov/entity/issues/26247
- Added magic link support for continuation In NRs
- Added magic link support for amalgamation NRs
- Refactored the code to make adding magic link support easier (moved common code to composable)
I added now to all routes to stay consistent. Let me know what you think.
In case we need to add any support for other filings in the future, it'll now be very easy 😁
> feat: magic link routes for Cont In and Amalg NRs + refactor

- business-registry-dashboard/app/components/BCReg/ContactInfo.vue
- business-registry-dashboard/app/components/Table/AffiliatedEntity/AffiliationLoadingError.vue
- business-registry-dashboard/app/components/Table/AffiliatedEntity/index.vue
- business-registry-dashboard/app/locales/en-CA.ts
- business-registry-dashboard/app/locales/fr-CA.ts
- business-registry-dashboard/app/stores/affiliations.ts
- business-registry-dashboard/nuxt.config.ts
- business-registry-dashboard/package.json
https://github.com/bcgov/entity/issues/26360
Design: https://www.figma.com/design/6MBqd7QAijpl6OXLvLXmos/Errors?node-id=8-554&p=f&m=dev
> feat: implemented design for table load error

- business-registry-dashboard/app/plugins/legal-api.ts
- business-registry-dashboard/app/utils/business.ts
- business-registry-dashboard/app/utils/namex-search.ts
- business-registry-dashboard/app/utils/reg-search.ts
- business-registry-dashboard/nuxt.config.ts
- business-registry-dashboard/package.json
- business-registry-dashboard/tests/unit/utils/business.test.ts
*Issue #:* bcgov/entity#26471
- app version = 1.0.27
- added app name to Nuxt config
- added App-Name to Legal API plugin
- added App-Name to business utils
- added App-Name to namex search utils
- added App-name to reg search utils
- fixed unit test
- updated app name in version string
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache 2.0).
> 26471 added App-Name to request headers

- .github/workflows/business-registry-ui-cd.yaml
> Revert "Update business-registry-ui-cd.yaml"

- business-registry-dashboard/.env.sample
- business-registry-dashboard/app/components/Table/AffiliatedEntity/index.vue
- business-registry-dashboard/app/enums/ld-flags.ts
- business-registry-dashboard/app/interfaces/affiliation.ts
- business-registry-dashboard/app/locales/en-CA.ts
- business-registry-dashboard/app/locales/fr-CA.ts
- business-registry-dashboard/app/stores/affiliations.ts
- business-registry-dashboard/nuxt.config.ts
- business-registry-dashboard/package.json
- business-registry-dashboard/tests/unit/stores/affiliations.test.ts
https://github.com/bcgov/entity/issues/26049
Enabled paging and server side filtering.
Keep in mind, the design here is purely created by me. This is for sure not going to be the final design. I also went with the assumption that the filtering + pagination is going to be done on the affiliations endpoint. This work here can be merged but is NOT final. Design is going to change. Architecture or the endpoint might ALSO change. I just worked with what I know at the moment.
> feat: implemented filters and paging to affiliations request

- business-registry-dashboard/app/components/Form/AddBusiness/Base.vue
- business-registry-dashboard/app/components/Form/AddBusiness/Error.vue
- business-registry-dashboard/app/components/Form/AddBusiness/index.vue
- business-registry-dashboard/app/components/HelpBusinessContact.vue
- business-registry-dashboard/app/components/Modal/ManageBusiness.vue
- business-registry-dashboard/app/locales/en-CA.ts
- business-registry-dashboard/app/locales/fr-CA.ts
- business-registry-dashboard/package.json
- business-registry-dashboard/tests/unit/components/Form/AddBusiness/Error.test.ts
- business-registry-dashboard/tests/unit/components/Form/AddBusiness/FormAddBusinessBase.test.ts
- business-registry-dashboard/tests/unit/components/Form/AddBusiness/index.test.ts
Issue: https://github.com/bcgov/entity/issues/26470
Description of changes:
Updates contain the following:
- Add in CCC/ULC and continued in business types
- Update modals to meet [new design](https://www.figma.com/design/e8EFtixUQ9sZiKKBSleXHq/Affiliation?node-id=2479-4465)
- Updated help section added
- Updates to affected tests
- Added in link placeholder for [Email Update form](https://app.zenhub.com/workspaces/digital-delivery-forms-space-6491dfdb3b6d5700272217c1/issues/gh/bcgov-registries/digital-delivery-forms/103)
- Updated wording in Eng and French
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).
> 26470-BRD manage business options update

- business-registry-dashboard/package.json
> 26470 Update package.json

- .github/workflows/person-roles-cd.yaml
- .github/workflows/person-roles-ci.yaml
- web/person-roles/.gcloudignore
- web/person-roles/firebase.json
[26866](https://github.com/bcgov/entity/issues/26866)
Update CI/CD settings
> CI/CD update.

- business-registry-dashboard/app/components/Modal/Base.vue
- business-registry-dashboard/app/components/Modal/RemoveBusiness/Generic.vue
- business-registry-dashboard/app/utils/business.ts
- business-registry-dashboard/package.json
https://github.com/bcgov/entity/issues/26607
Now the close button is aligned with the alert icon:
I'm thinking I don't update the package version since last PR missed 1.0.33:
https://github.com/bcgov/business-ui/pull/95/files
> 26607 fix: fixed in response to UXA notes

- business-registry-dashboard/app/components/Modal/ManageBusiness.vue
- business-registry-dashboard/package.json
*Issue:*https://github.com/bcgov/entity/issues/26470
Update to make 'close' button right aligned.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).
> 26470-update to button alignment

- business-registry-dashboard/app/components/Form/AddBusiness/EmailAuthSent.vue
- business-registry-dashboard/package.json
*Issue:*https://github.com/bcgov/entity/issues/26470
Description:
Update to button alignment for email sent modals
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).
> 26470 - aligning close button on email sent modal

- web/person-roles/app/components/Form/OfficerChange/index.vue
- web/person-roles/app/components/Table/OfficerChange/index.vue
- web/person-roles/i18n/locales/en-CA.ts
- web/person-roles/package.json
https://github.com/bcgov/entity/issues/26965
- add empty text to table (prop not working so used slot instead)
- update name to legal name
> 26965 - Officer ux update

- .github/CODEOWNERS
- business-registry-dashboard/app/components/Table/AffiliatedEntity/StatusDetails.vue
- business-registry-dashboard/app/components/Table/AffiliatedEntity/index.vue
- business-registry-dashboard/app/enums/display-name-to-corp-type.ts
- business-registry-dashboard/app/stores/affiliations.ts
- business-registry-dashboard/app/utils/affiliations.ts
- business-registry-dashboard/package.json
https://github.com/bcgov/entity/issues/26916 and https://github.com/bcgov/entity/issues/26087
- Fixed the filtering. It was bugged for not in good standing. When a filter was being selected, wrong alerts were being shown. That is fixed now.
- Added tons of comments to explain the alerts + filtering process for future Devs. Lots of stuff is going there.
- Fixed the type filter call that is made to the backend. This'll help Rajan continue with her work
- Misc. fixes
> fixes: fixed filtering + Auth API filter call + misc. fixes

- web/person-roles/app/app.config.ts
- web/person-roles/app/components/Connect/ButtonControl.vue
- web/person-roles/app/components/Connect/DetailHeader/Item.vue
- web/person-roles/app/components/Connect/DetailHeader/index.vue
- web/person-roles/app/components/Connect/Fee/ExtraFee.vue
- web/person-roles/app/components/Connect/Fee/Widget.vue
- web/person-roles/app/components/Connect/Transition/Collapse.vue
- web/person-roles/app/components/Form/OfficerChange/index.vue
- web/person-roles/app/components/Table/OfficerChange/index.vue
- web/person-roles/app/composables/useButtonControl.ts
- web/person-roles/app/enums/connect-pay-cfs-status.ts
- web/person-roles/app/enums/connect-payment-method.ts
- web/person-roles/app/interfaces/connect-btn-control.ts
- web/person-roles/app/interfaces/connect-detail-header.ts
- web/person-roles/app/interfaces/connect-fees.ts
- web/person-roles/app/interfaces/connect-pay-account.ts
- web/person-roles/app/layouts/form.vue
- web/person-roles/app/pages/officer-change.vue
- web/person-roles/app/stores/connect-details-header.ts
- web/person-roles/app/stores/connect-fee.ts
- web/person-roles/app/utils/sleep.ts
- web/person-roles/i18n/locales/en-CA.ts
- web/person-roles/package.json
> 27070 - Officer initial form layout (header, footer, fee widget)

- web/person-roles/app/components/Table/OfficerChange/index.vue
- web/person-roles/app/stores/officer.ts
- web/person-roles/package.json
- fix expanded border
- fix error border
- fix roles not updating in existing officer
> Officers - Minor ux fixes

- business-registry-dashboard/app/components/Modal/CoopContinuationIn.vue
- business-registry-dashboard/app/locales/en-CA.ts
- business-registry-dashboard/app/locales/fr-CA.ts
- business-registry-dashboard/package.json
https://github.com/bcgov/entity/issues/27125
Fixed the numbers in the continuation in coop dialog.
Before:
After:
> 27125 - Fixed the contact info numbers for coop cont in dialog

- business-registry-dashboard/app/components/Table/AffiliatedEntity/index.vue
- business-registry-dashboard/app/locales/en-CA.ts
- business-registry-dashboard/app/locales/fr-CA.ts
- business-registry-dashboard/app/stores/affiliations.ts
- business-registry-dashboard/package.json
- business-registry-dashboard/tests/unit/stores/affiliations.test.ts
https://github.com/bcgov/entity/issues/27079 + https://github.com/bcgov/entity/issues/27148
- Implemented the ability to filter by multiple options at the same time
- Filtering will also work for when we have the page limit and pagination enabled
- Fixed unit tests
- Misc. fixes
> 27079 and 27148 - Implemented multiple option filtering + pagination updates

- web/person-roles/app/components/Form/OfficerChange/index.vue
- web/person-roles/app/components/Table/OfficerChange/index.vue
- web/person-roles/app/interfaces/business/org-person.ts
- web/person-roles/app/stores/officer.ts
- web/person-roles/app/utils/validate/address/mailing.ts
- web/person-roles/i18n/locales/en-CA.ts
- web/person-roles/package.json
partial: bcgov/entity#27263
- update table actions to match v3 design
- full form in edit mode instead of sections
- remove nested forms as not needed anymore due to full form
- simplify officer store actions, add comments
> 27263 - Officer - Full form in edit mode

- business-registry-dashboard/app/stores/affiliations.ts
- business-registry-dashboard/package.json
https://github.com/bcgov/entity/issues/27148
Changed how filtering is passed based on a request from Rajan.
> 27148 - Changed how server side filtering is passed to BE

- business-registry-dashboard/app/components/Form/AddBusiness/Base.vue
- business-registry-dashboard/package.json
https://github.com/bcgov/entity/issues/27068
> 27068 - Explicitly put the type in the payload for magic link

- business-registry-dashboard/app/stores/affiliations.ts
- business-registry-dashboard/app/utils/date.ts
- business-registry-dashboard/nuxt.config.ts
- business-registry-dashboard/package.json
- business-registry-dashboard/pnpm-lock.yaml
https://github.com/bcgov/entity/issues/28443
Fixed a bug that Sev found.
The bug: If the type or status filters are changed while the table is loading, they're not picked up. For example, I put an Active status filter. The table loads. While the table is loading, I select draft. After loading is finished, the drafts are not seen, only the Active ones.
> 28443 - Fixed server side type and status filtering bugs

- web/business-registry-dashboard/app/locales/en-CA.ts
- web/business-registry-dashboard/app/locales/fr-CA.ts
- web/business-registry-dashboard/package.json
https://github.com/bcgov/entity/issues/29067
as per https://github.com/bcgov/entity/issues/29067#issuecomment-3006116273
> 29067 - Fixed wording as per UXA notes

- web/business-registry-dashboard/app/components/Table/AffiliatedEntity/Action.vue
- web/business-registry-dashboard/package.json
https://github.com/bcgov/entity/issues/29252
I could not test this because of DEV issues. NRs are not showing. I'm kind of going blindfolded here but most probably this is going to work.
UDATE: I actually tested this in TEST. I'm certain this will fix the issue.
> 29252 - Fix NR Conditionally approved cannot be used

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/post-restoration-transition-application-cd.yaml
- .github/workflows/post-restoration-transition-application-ci.yaml
*Issue #:29115* /bcgov/entity###
- add CD file
- update app name in CI files
- add githup PR template
> 29115 ci/cd deployment

- web/post-restoration-transition-application/app/components/Connect/Form/Input.vue
- web/post-restoration-transition-application/app/components/Connect/Form/Section.vue
- web/post-restoration-transition-application/app/components/Form/Certify.vue
- web/post-restoration-transition-application/app/components/Form/SubSection.vue
- web/post-restoration-transition-application/app/pages/[businessId].vue
- web/post-restoration-transition-application/app/stores/post-restoration-transition-application.ts
- web/post-restoration-transition-application/app/utils/uidate.ts
- web/post-restoration-transition-application/i18n/locales/en-CA.ts
Issue #:28828 /bcgov/entity###
Description of changes:
- add certify component
- replace some existing DIVs and Html headers with sections
> 28828 certify component

- web/person-roles/.env.example
- web/person-roles/app/components/Connect/Fee/Widget.vue
- web/person-roles/app/composables/useLegalApi.ts
- web/person-roles/app/interfaces/business-filing.ts
- web/person-roles/app/pages/officer-change/[businessId].vue
- web/person-roles/app/stores/connect-fee.ts
- web/person-roles/app/stores/officer.ts
- web/person-roles/app/utils/format-officer.ts
- web/person-roles/devops/vaults.env
- web/person-roles/i18n/locales/en-CA.ts
*Issue #:* bcgov/entity#29298
- add alternate payment method to fee widget
- create filing payload helper
- add types for filing submission data
- organize error text in i18n file
- update vault.env with base url bcgov/entity#29269
> 29298 - pay update

- web/post-restoration-transition-application/app/app.config.ts
- web/post-restoration-transition-application/app/components/Form/Certify.vue
- web/post-restoration-transition-application/app/pages/[businessId].vue
- web/post-restoration-transition-application/i18n/locales/en-CA.ts
- web/post-restoration-transition-application/nuxt.config.ts
*Issue #:28924 * /bcgov/entity#28924
- add company provisions sections
- update base styling for the link
> 28924 company provisions

- web/person-roles/app/components/Table/OfficerChange/index.vue
- web/person-roles/app/stores/officer.ts
- web/person-roles/i18n/locales/en-CA.ts
- web/person-roles/package.json
*Issue #:* bcgov/entity#29370
- update error modal text and buttons
- update undo buttons
- undo is main action when available
- undo reverts all changes (not step by step)   
> 29370 - officers - v5 updates

- web/person-roles/app/components/Form/Checkbox/Group.vue
- web/person-roles/app/components/Form/Checkbox/Item.vue
- web/person-roles/app/components/Form/OfficerChange/index.vue
- web/person-roles/app/interfaces/business-filing.ts
- web/person-roles/eslint.config.mjs
- web/person-roles/package.json
- web/person-roles/pnpm-lock.yaml
- web/person-roles/tests/e2e/setup.ts
- web/person-roles/tests/e2e/test-utils/a11y.ts
*Issue #:* /bcgov/entity###
- update dependencies
> officers - update all deps

- web/business-registry-dashboard/app/components/Table/AffiliatedEntity/Action.vue
- web/business-registry-dashboard/package.json
*Issue #:* /bcgov/entity#29252
This has been causing a lot of ops issues and calls. I decided to scrap the whole thing. People are getting confused as to what's happening.
> 29252 - Fixed conditionally approved NRs not working

- web/person-roles/app/app.config.ts
- web/person-roles/app/assets/css/tw.css
- web/person-roles/app/components/Connect/Address/Display.vue
- web/person-roles/app/components/Connect/ButtonControl.vue
- web/person-roles/app/components/Connect/Fee/Widget.vue
- web/person-roles/app/components/Connect/Input.vue
- web/person-roles/app/components/Connect/Textarea.vue
- web/person-roles/app/components/Form/Address/Country.vue
- web/person-roles/app/components/Form/Address/Region.vue
- web/person-roles/app/components/Table/OfficerChange/index.vue
- web/person-roles/package.json
*Issue #:* /bcgov/entity#28952
- fix floating labels on safari
- update address display (remove location description label and make content italic)
- button control footer padding
- fix padding/text size in fee summary
- sort roles when displayed in table
- text/icon colour in dropdown menu
- focus text colour in select menus
- remove border opacity from 'outline' variant button
**Does not include comparing the original office state to the new state when in edit mode, this will require a bigger change. I will create a new ticket for that.**
> Officer Change - V4 uxa

- web/post-restoration-transition-application/app/components/Form/DateInput.vue
- web/post-restoration-transition-application/app/components/Form/DateInputWithButtons.vue
- web/post-restoration-transition-application/app/components/Form/SubSection.vue
- web/post-restoration-transition-application/app/pages/[businessId].vue
*Issue #:29098 * /bcgov/entity#29098 
- css updates for padding
- adding date select popup on blur
- adding min/max dates for articles date selection
> 29098 ux updates

- web/business-registry-dashboard/app/composables/useAccountValidation.ts
- web/business-registry-dashboard/package.json
*Issue #:* /bcgov/entity#29824
> 29824 incomplete_account_setup_dialog

- web/post-restoration-transition-application/devops/vaults.env
*Issue #:* /bcgov/entity###
fix where keycloak client gets the key from
> fix: update keycloak client

- web/person-roles/app/components/Connect/DetailHeader/index.vue
- web/person-roles/app/components/Form/Address/index.vue
- web/person-roles/app/components/Form/OfficerChange/index.vue
- web/person-roles/app/components/Form/Section.vue
- web/person-roles/app/components/Table/OfficerChange/index.vue
- web/person-roles/app/interfaces/business/auth-information.ts
- web/person-roles/app/pages/officer-change/[businessId].vue
- web/person-roles/app/stores/officer.ts
- web/person-roles/app/types/officer.ts
- web/person-roles/i18n/locales/en-CA.ts
- web/person-roles/package.json
- web/person-roles/tests/unit/stores/officer.spec.ts
*Issues:* 
- bcgov/entity#29959
- bcgov/entity#29775
- bcgov/entity#29884
- bcgov/entity#29886
- bcgov/entity#29885
- bcgov/entity#29818
- update folio layout and validation
- validate folio number on submit
- add entity folionumber to filing if it exists on submit
- add folio number to 'hasChanges' check
- minor styling updates on error messages/when to clear
- update some error modal text/buttons
- fix font colour in business tombstone 
> Officers - V5 updates/folio

- web/business-registry-dashboard/app/components/Modal/ManageBusiness.vue
- web/business-registry-dashboard/package.json
*Issue #:* /bcgov/entity#29789
Design - https://www.figma.com/design/e8EFtixUQ9sZiKKBSleXHq/Affiliation?node-id=2928-10643&p=f&focus-id=3222-760&m=dev
1. Business is in LEAR
2. Business is in COLIN
> 29789 bc company affiliation error message part_2

- web/post-restoration-transition-application/app/components/Form/DateInputWithButtons.vue
- web/post-restoration-transition-application/app/composables/useStandaloneTransitionButtons.ts
- web/post-restoration-transition-application/app/interfaces/addresses.ts
- web/post-restoration-transition-application/app/interfaces/shares.ts
- web/post-restoration-transition-application/app/interfaces/standalone-transition.ts
- web/post-restoration-transition-application/app/pages/[businessId].vue
- web/post-restoration-transition-application/app/stores/post-restoration-transition-application.ts
- web/post-restoration-transition-application/app/types/nuxt-hooks.d.ts
- web/post-restoration-transition-application/tests/e2e/examples/full-filing.json
- web/post-restoration-transition-application/tests/e2e/examples/mandatory-filing.json
*Issue #:28832 * /bcgov/entity#28832 
- adding filing buttons (save, save and resume, cancel, submit)
- adding button behavior
> 28832 button behavior

- web/business-registry-dashboard/app/components/Table/AffiliatedEntity/index.vue
- web/business-registry-dashboard/app/stores/affiliations.ts
- web/business-registry-dashboard/package.json
*Issue #:* /bcgov/entity#29888
> 29888 update_header_filter

- web/business-registry-dashboard/app/components/Table/AffiliatedEntity/StatusDetails.vue
- web/business-registry-dashboard/app/utils/affiliations.ts
*Issue #:* /bcgov/entity#29847
Updated condition
> 29847 - Updated fix for expired nrs

- web/business-registry-dashboard/app/utils/business.ts
- web/business-registry-dashboard/package.json
- web/business-registry-dashboard/tests/unit/utils/affiliations.test.ts
*Issue #:* /bcgov/entity#30273
> 30273 fix business lear check

- .changeset/blue-bags-say.md
- .changeset/config.json
- packages/layers/base/nuxt.config.ts
- packages/layers/base/package.json
- pnpm-lock.yaml
- web/person-roles/app/assets/css/tw.css
- web/person-roles/app/components/Form/OfficerChange/index.vue
- web/person-roles/app/composables/useLegalApi.ts
- web/person-roles/app/pages/officer-change/[businessId].vue
- web/person-roles/app/plugins/legal-api.ts
- web/person-roles/app/stores/officer.ts
- web/person-roles/app/utils/officer-helpers.ts
- web/person-roles/nuxt.config.ts
- web/person-roles/package.json
- web/person-roles/tests/mocks/i18n.ts
*Issue #:* bcgov/entity#29332
- minimal changes to add connect-nuxt layers to person-roles via business-base layer
- styling/refactoring to be done in future PRs
> Add Connect layers to business layer

- web/post-restoration-transition-application/app/assets/css/tw.css
- web/post-restoration-transition-application/app/components/Form/DateInput.vue
- web/post-restoration-transition-application/app/components/Form/DateInputWithButtons.vue
- web/post-restoration-transition-application/app/components/Form/DatePicker.vue
- web/post-restoration-transition-application/app/components/Shares/AddEdit.vue
- web/post-restoration-transition-application/app/interfaces/articles.ts
- web/post-restoration-transition-application/app/pages/[businessId].vue
- web/post-restoration-transition-application/app/utils/uidate.ts
- web/post-restoration-transition-application/i18n/locales/en-CA.ts
*Issue #:29867 * /bcgov/entity#29867
- update validation for articles
- update styles for filing buttons
- update some other styles to make app more consistent
> 29867 articles validation styles updates

- .github/workflows/person-roles-cd.yaml
- web/person-roles/package.json
*Issue #:* /bcgov/entity#29341
> test new workflow

- .github/workflows/person-roles-cd.yaml
- .github/workflows/person-roles-ci.yaml
*Issue #:* /bcgov/entity#29341
> Update person roles ci

- .changeset/tender-toys-agree.md
- packages/layers/base/package.json
- packages/layers/base/tests/e2e/specs/example.spec.ts
- pnpm-lock.yaml
- web/person-roles/app/app.config.ts
- web/person-roles/app/middleware/mock-connect-auth.ts
- web/person-roles/app/pages/officer-change/[businessId].vue
*Issue #:* bcgov/entity#29341
- update nuxt-pay version in layer
- switch to auth pages from auth layer
- cleanup middleware
> Cleanup middleware

- web/post-restoration-transition-application/app/components/Form/AddressChange.vue
- web/post-restoration-transition-application/app/components/Form/DateInputWithButtons.vue
- web/post-restoration-transition-application/app/components/Shares/AddEdit.vue
- web/post-restoration-transition-application/app/components/Shares/Index.vue
- web/post-restoration-transition-application/app/composables/useEditFormHandlers.ts
- web/post-restoration-transition-application/app/composables/useStandaloneTransitionButtons.ts
- web/post-restoration-transition-application/app/enum/page_sections.ts
- web/post-restoration-transition-application/app/pages/[businessId].vue
- web/post-restoration-transition-application/app/stores/errors.ts
- web/post-restoration-transition-application/app/stores/post-restoration-transition-application.ts
- web/post-restoration-transition-application/i18n/locales/en-CA.ts
- web/post-restoration-transition-application/nuxt.config.ts
- web/post-restoration-transition-application/package.json
- web/post-restoration-transition-application/pnpm-lock.yaml
- web/post-restoration-transition-application/tests/e2e/specs/stop-on-open-form.spec.ts
- web/post-restoration-transition-application/tests/e2e/specs/validations.spec.ts
*Issue #:29620 * /bcgov/entity#29620 
- adding check for open edit forms on page
- stop submission
- stop from opening other blocking forms 
> 29620 check for open edit form on submit and on triggers

- web/post-restoration-transition-application/app/pages/[businessId].vue
*Issue #:* /bcgov/entity#29866
Made modal show error when no date entered and submitted
> show error in modal when no date entered

- web/business-registry-dashboard/app/utils/affiliations.ts
- web/business-registry-dashboard/package.json
*Issue #:* /bcgov/entity#30253
1. Error on the Dev
- Consumed
- Expired
2. Preview
- Consumed
- Expired
> 30253 fix status warning details

- web/person-roles/package.json
- web/person-roles/pnpm-lock.yaml
> add test deps
